### ISSUE TITLE
Missing Pi Model

### ISSUE THREAD

**Issue by axwaxw** [launchcodedev/pi-camera-connect#26]
My pi _**model**_ was missing.  I have added it to the list locally:

    static async getJpegSignature() {
         const systemInfo = await si.system();
         switch (systemInfo.model) {
             case 'BCM2711':
             case 'BCM2835 - Pi 3 Model B':
             case 'BCM2835 - Pi 3 Model B+':
             case 'BCM2835 - Pi 4 Model B':
             case 'BCM2835 - Pi Zero':
             case 'BCM2835 - Pi Zero W':
             case 'Raspberry Pi 4 Model B Rev 1.1': // <-------------------------- HERE
                 return Buffer.from([0xff, 0xd8, 0xff, 0xdb, 0x00, 0x84, 0x00]);
             default:
                 throw new Error(`Could not determine JPEG signature. Unknown system model '${systemInfo.model}'`);
         }
     }

**Comment by hansnn** [comment]
Same here, except my version is 'Raspberry Pi 3 Model B Rev 1.2'

**Comment by gregnr** [comment]
Hi @axwaxw, thanks for the issue. We have received a number of reports now about Pi model breaking.

As a fix we have decided to remove the Pi model check altogether, since so far every model appears to use the same JPEG signature. This makes the library less brittle to changes that are outside of our control.

More details can be found here: https://github.com/launchcodedev/pi-camera-connect/pull/23#issuecomment-743941448

This change is available now on [v0.3.4](https://github.com/launchcodedev/pi-camera-connect/releases/tag/v0.3.4).
