### ISSUE TITLE
ISO values not changing

### ISSUE THREAD

**Issue by Vidhyanandcs** [launchcodedev/pi-camera-connect#29]
ISO is not changing. I tried the  following. 

`    
     const fs = require('fs')
     const { StillCamera } = require('pi-camera-connect')

    const stillCameraWP = new StillCamera({
        delay: 750, 
        iso: 6
    })

    const image1 = await stillCameraWP.takeImage()
`
Please let me know if this is the right method...

**Comment by gregnr** [comment]
Hi @Vidhyanandcs thanks for the issue. ISO should be in the 100 - 800 range. I've updated the [README](https://github.com/launchcodedev/pi-camera-connect/blob/master/README.md#constructor-options-stilloptions-stillcamera) to include this.

Since this library uses `raspistill`/`raspivid` under the hood, you can also reference their documentation for additional details: 
https://www.raspberrypi.org/documentation/raspbian/applications/camera.md

Please let me know if this works.

**Comment by gregnr** [comment]
@Vidhyanandcs closing this issue for cleanup purposes. I hope the above answer helped but feel free to reopen this if you have further issues.
